# baseURL = "https://link.techhut.tv/"
languageCode = "en"
defaultContentLanguage = "en"

title = "TechHut Media Directory"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "TechHut"
  headline = "Contact information, social media, and other links for Brandon Hopkins, founder and host of TechHut. Bringing detailed guides, tutorials, tips-and-tricks! We're casual gamers, tech enthusiasts, open source advocates, and simply; geeks."
  # image = "img/author.jpg"  # path relative to static directory

  links = [
    { email = "mailto:brandon@techhut.tv" },
    # { link = "https://buymeacoffee.com/techhut" },
    { amazon = "https://www.amazon.com/shop/techhut" },
    { bluesky = "https://bsky.app/profile/techhut.bsky.social" },
    # { discord = "https://discord.gg/invitecode" },
    { facebook = "https://www.facebook.com/TechHutHD/" },
    { github = "https://github.com/TechHutTV/" },
    { instagram = "https://www.instagram.com/brandonhopkins/" },
    # { linkedin = "https://linkedin.com/in/username" },
    { mastodon = "https://fosstodon.org/@techhut" },
    # { medium = "https://medium.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { twitch = "https://twitch.tv/username" },
    # { whatsapp = "https://wa.me/xxxxx" },
    { x = "https://x.com/techhuttv" },
    { youtube = "https://youtube.com/@techhut" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
